
CREATE TABLE  Country (
     code   char (3) NOT NULL,
     name   varchar (50) NOT NULL
);

INSERT INTO Country (name, code) values ('Afghanistan','AF ');
INSERT INTO Country (name, code) values ('Aland Islands','AX ');
INSERT INTO Country (name, code) values ('Albania','AL ');
INSERT INTO Country (name, code) values ('Algeria','DZ ');
INSERT INTO Country (name, code) values ('American Samoa','AS ');
INSERT INTO Country (name, code) values ('Andorra','AD ');
INSERT INTO Country (name, code) values ('Angola','AO ');
INSERT INTO Country (name, code) values ('Anguilla','AI ');
INSERT INTO Country (name, code) values ('Antarctica','AQ ');
INSERT INTO Country (name, code) values ('Antigua and Barbuda','AG ');
INSERT INTO Country (name, code) values ('Argentina','AR ');
INSERT INTO Country (name, code) values ('Armenia','AM ');
INSERT INTO Country (name, code) values ('Aruba','AW ');
INSERT INTO Country (name, code) values ('Australia','AU ');
INSERT INTO Country (name, code) values ('Austria','AT ');
INSERT INTO Country (name, code) values ('Azerbaijan','AZ ');
INSERT INTO Country (name, code) values ('Bahamas','BS ');
INSERT INTO Country (name, code) values ('Bahrain','BH ');
INSERT INTO Country (name, code) values ('Bangladesh','BD ');
INSERT INTO Country (name, code) values ('Barbados','BB ');
INSERT INTO Country (name, code) values ('Belarus','BY ');
INSERT INTO Country (name, code) values ('Belgium','BE ');
INSERT INTO Country (name, code) values ('Belize','BZ ');
INSERT INTO Country (name, code) values ('Benin','BJ ');
INSERT INTO Country (name, code) values ('Bermuda','BM ');
INSERT INTO Country (name, code) values ('Bhutan','BT ');
INSERT INTO Country (name, code) values ('Bolivia','BO ');
INSERT INTO Country (name, code) values ('Bosnia and Herzegovina','BA ');
INSERT INTO Country (name, code) values ('Botswana','BW ');
INSERT INTO Country (name, code) values ('Bouvet Island','BV ');
INSERT INTO Country (name, code) values ('Brazil','BR ');
INSERT INTO Country (name, code) values ('British Virgin Islands','VG ');
INSERT INTO Country (name, code) values ('British Indian Ocean Territory','IO ');
INSERT INTO Country (name, code) values ('Brunei Darussalam','BN ');
INSERT INTO Country (name, code) values ('Bulgaria','BG ');
INSERT INTO Country (name, code) values ('Burkina Faso','BF ');
INSERT INTO Country (name, code) values ('Burundi','BI ');
INSERT INTO Country (name, code) values ('Cambodia','KH ');
INSERT INTO Country (name, code) values ('Cameroon','CM ');
INSERT INTO Country (name, code) values ('Canada','CA ');
INSERT INTO Country (name, code) values ('Cape Verde','CV ');
INSERT INTO Country (name, code) values ('Cayman Islands','KY ');
INSERT INTO Country (name, code) values ('Central African Republic','CF ');
INSERT INTO Country (name, code) values ('Chad','TD ');
INSERT INTO Country (name, code) values ('Chile','CL ');
INSERT INTO Country (name, code) values ('China','CN ');
INSERT INTO Country (name, code) values ('Hong Kong, Special Administrative Region of China','HK ');
INSERT INTO Country (name, code) values ('Macao, Special Administrative Region of China','MO ');
INSERT INTO Country (name, code) values ('Christmas Island','CX ');
INSERT INTO Country (name, code) values ('Cocos (Keeling) Islands','CC ');
INSERT INTO Country (name, code) values ('Colombia','CO ');
INSERT INTO Country (name, code) values ('Comoros','KM ');
INSERT INTO Country (name, code) values ('Congo (Brazzaville)','CG ');
INSERT INTO Country (name, code) values ('Congo, Democratic Republic of the','CD ');
INSERT INTO Country (name, code) values ('Cook Islands','CK ');
INSERT INTO Country (name, code) values ('Costa Rica','CR ');
INSERT INTO Country (name, code) values ('Cote dIvoire','CI ');
INSERT INTO Country (name, code) values ('Croatia','HR ');
INSERT INTO Country (name, code) values ('Cuba','CU ');
INSERT INTO Country (name, code) values ('Cyprus','CY ');
INSERT INTO Country (name, code) values ('Czech Republic','CZ ');
INSERT INTO Country (name, code) values ('Denmark','DK ');
INSERT INTO Country (name, code) values ('Djibouti','DJ ');
INSERT INTO Country (name, code) values ('Dominica','DM ');
INSERT INTO Country (name, code) values ('Dominican Republic','DO ');
INSERT INTO Country (name, code) values ('Ecuador','EC ');
INSERT INTO Country (name, code) values ('Egypt','EG ');
INSERT INTO Country (name, code) values ('El Salvador','SV ');
INSERT INTO Country (name, code) values ('Equatorial Guinea','GQ ');
INSERT INTO Country (name, code) values ('Eritrea','ER ');
INSERT INTO Country (name, code) values ('Estonia','EE ');
INSERT INTO Country (name, code) values ('Ethiopia','ET ');
INSERT INTO Country (name, code) values ('Falkland Islands (Malvinas)','FK ');
INSERT INTO Country (name, code) values ('Faroe Islands','FO ');
INSERT INTO Country (name, code) values ('Fiji','FJ ');
INSERT INTO Country (name, code) values ('Finland','FI ');
INSERT INTO Country (name, code) values ('France','FR ');
INSERT INTO Country (name, code) values ('French Guiana','GF ');
INSERT INTO Country (name, code) values ('French Polynesia','PF ');
INSERT INTO Country (name, code) values ('French Southern Territories','TF ');
INSERT INTO Country (name, code) values ('Gabon','GA ');
INSERT INTO Country (name, code) values ('Gambia','GM ');
INSERT INTO Country (name, code) values ('Georgia','GE ');
INSERT INTO Country (name, code) values ('Germany','DE ');
INSERT INTO Country (name, code) values ('Ghana','GH ');
INSERT INTO Country (name, code) values ('Gibraltar','GI ');
INSERT INTO Country (name, code) values ('Greece','GR ');
INSERT INTO Country (name, code) values ('Greenland','GL ');
INSERT INTO Country (name, code) values ('Grenada','GD ');
INSERT INTO Country (name, code) values ('Guadeloupe','GP ');
INSERT INTO Country (name, code) values ('Guam','GU ');
INSERT INTO Country (name, code) values ('Guatemala','GT ');
INSERT INTO Country (name, code) values ('Guernsey','GG ');
INSERT INTO Country (name, code) values ('Guinea','GN ');
INSERT INTO Country (name, code) values ('Guinea-Bissau','GW ');
INSERT INTO Country (name, code) values ('Guyana','GY ');
INSERT INTO Country (name, code) values ('Haiti','HT ');
INSERT INTO Country (name, code) values ('Heard Island and Mcdonald Islands','HM ');
INSERT INTO Country (name, code) values ('Holy See (Vatican City State)','VA ');
INSERT INTO Country (name, code) values ('Honduras','HN ');
INSERT INTO Country (name, code) values ('Hungary','HU ');
INSERT INTO Country (name, code) values ('Iceland','IS ');
INSERT INTO Country (name, code) values ('India','IN ');
INSERT INTO Country (name, code) values ('Indonesia','ID ');
INSERT INTO Country (name, code) values ('Iran, Islamic Republic of','IR ');
INSERT INTO Country (name, code) values ('Iraq','IQ ');
INSERT INTO Country (name, code) values ('Ireland','IE ');
INSERT INTO Country (name, code) values ('Isle of Man','IM ');
INSERT INTO Country (name, code) values ('Israel','IL ');
INSERT INTO Country (name, code) values ('Italy','IT ');
INSERT INTO Country (name, code) values ('Jamaica','JM ');
INSERT INTO Country (name, code) values ('Japan','JP ');
INSERT INTO Country (name, code) values ('Jersey','JE ');
INSERT INTO Country (name, code) values ('Jordan','JO ');
INSERT INTO Country (name, code) values ('Kazakhstan','KZ ');
INSERT INTO Country (name, code) values ('Kenya','KE ');
INSERT INTO Country (name, code) values ('Kiribati','KI ');
INSERT INTO Country (name, code) values ('Korea, Democratic Peoples Republic of','KP ');
INSERT INTO Country (name, code) values ('Korea, Republic of','KR ');
INSERT INTO Country (name, code) values ('Kuwait','KW ');
INSERT INTO Country (name, code) values ('Kyrgyzstan','KG ');
INSERT INTO Country (name, code) values ('Lao PDR','LA ');
INSERT INTO Country (name, code) values ('Latvia','LV ');
INSERT INTO Country (name, code) values ('Lebanon','LB ');
INSERT INTO Country (name, code) values ('Lesotho','LS ');
INSERT INTO Country (name, code) values ('Liberia','LR ');
INSERT INTO Country (name, code) values ('Libya','LY ');
INSERT INTO Country (name, code) values ('Liechtenstein','LI ');
INSERT INTO Country (name, code) values ('Lithuania','LT ');
INSERT INTO Country (name, code) values ('Luxembourg','LU ');
INSERT INTO Country (name, code) values ('Macedonia, Republic of','MK ');
INSERT INTO Country (name, code) values ('Madagascar','MG ');
INSERT INTO Country (name, code) values ('Malawi','MW ');
INSERT INTO Country (name, code) values ('Malaysia','MY ');
INSERT INTO Country (name, code) values ('Maldives','MV ');
INSERT INTO Country (name, code) values ('Mali','ML ');
INSERT INTO Country (name, code) values ('Malta','MT ');
INSERT INTO Country (name, code) values ('Marshall Islands','MH ');
INSERT INTO Country (name, code) values ('Martinique','MQ ');
INSERT INTO Country (name, code) values ('Mauritania','MR ');
INSERT INTO Country (name, code) values ('Mauritius','MU ');
INSERT INTO Country (name, code) values ('Mayotte','YT ');
INSERT INTO Country (name, code) values ('Mexico','MX ');
INSERT INTO Country (name, code) values ('Micronesia, Federated States of','FM ');
INSERT INTO Country (name, code) values ('Moldova','MD ');
INSERT INTO Country (name, code) values ('Monaco','MC ');
INSERT INTO Country (name, code) values ('Mongolia','MN ');
INSERT INTO Country (name, code) values ('Montenegro','ME ');
INSERT INTO Country (name, code) values ('Montserrat','MS ');
INSERT INTO Country (name, code) values ('Morocco','MA ');
INSERT INTO Country (name, code) values ('Mozambique','MZ ');
INSERT INTO Country (name, code) values ('Myanmar','MM ');
INSERT INTO Country (name, code) values ('Namibia','NA ');
INSERT INTO Country (name, code) values ('Nauru','NR ');
INSERT INTO Country (name, code) values ('Nepal','NP ');
INSERT INTO Country (name, code) values ('Netherlands','NL ');
INSERT INTO Country (name, code) values ('Netherlands Antilles','AN ');
INSERT INTO Country (name, code) values ('New Caledonia','NC ');
INSERT INTO Country (name, code) values ('New Zealand','NZ ');
INSERT INTO Country (name, code) values ('Nicaragua','NI ');
INSERT INTO Country (name, code) values ('Niger','NE ');
INSERT INTO Country (name, code) values ('Nigeria','NG ');
INSERT INTO Country (name, code) values ('Niue','NU ');
INSERT INTO Country (name, code) values ('Norfolk Island','NF ');
INSERT INTO Country (name, code) values ('Northern Mariana Islands','MP ');
INSERT INTO Country (name, code) values ('Norway','NO ');
INSERT INTO Country (name, code) values ('Oman','OM ');
INSERT INTO Country (name, code) values ('Pakistan','PK ');
INSERT INTO Country (name, code) values ('Palau','PW ');
INSERT INTO Country (name, code) values ('Palestinian Territory, Occupied','PS ');
INSERT INTO Country (name, code) values ('Panama','PA ');
INSERT INTO Country (name, code) values ('Papua New Guinea','PG ');
INSERT INTO Country (name, code) values ('Paraguay','PY ');
INSERT INTO Country (name, code) values ('Peru','PE ');
INSERT INTO Country (name, code) values ('Philippines','PH ');
INSERT INTO Country (name, code) values ('Pitcairn','PN ');
INSERT INTO Country (name, code) values ('Poland','PL ');
INSERT INTO Country (name, code) values ('Portugal','PT ');
INSERT INTO Country (name, code) values ('Puerto Rico','PR ');
INSERT INTO Country (name, code) values ('Qatar','QA ');
INSERT INTO Country (name, code) values ('Réunion','RE ');
INSERT INTO Country (name, code) values ('Romania','RO ');
INSERT INTO Country (name, code) values ('Russian Federation','RU ');
INSERT INTO Country (name, code) values ('Rwanda','RW ');
INSERT INTO Country (name, code) values ('Saint-Barthélemy','BL ');
INSERT INTO Country (name, code) values ('Saint Helena','SH ');
INSERT INTO Country (name, code) values ('Saint Kitts and Nevis','KN ');
INSERT INTO Country (name, code) values ('Saint Lucia','LC ');
INSERT INTO Country (name, code) values ('Saint-Martin (French part)','MF ');
INSERT INTO Country (name, code) values ('Saint Pierre and Miquelon','PM ');
INSERT INTO Country (name, code) values ('Saint Vincent and Grenadines','VC ');
INSERT INTO Country (name, code) values ('Samoa','WS ');
INSERT INTO Country (name, code) values ('San Marino','SM ');
INSERT INTO Country (name, code) values ('Sao Tome and Principe','ST ');
INSERT INTO Country (name, code) values ('Saudi Arabia','SA ');
INSERT INTO Country (name, code) values ('Senegal','SN ');
INSERT INTO Country (name, code) values ('Serbia','RS ');
INSERT INTO Country (name, code) values ('Seychelles','SC ');
INSERT INTO Country (name, code) values ('Sierra Leone','SL ');
INSERT INTO Country (name, code) values ('Singapore','SG ');
INSERT INTO Country (name, code) values ('Slovakia','SK ');
INSERT INTO Country (name, code) values ('Slovenia','SI ');
INSERT INTO Country (name, code) values ('Solomon Islands','SB ');
INSERT INTO Country (name, code) values ('Somalia','SO ');
INSERT INTO Country (name, code) values ('South Africa','ZA ');
INSERT INTO Country (name, code) values ('South Georgia and the South Sandwich Islands','GS ');
INSERT INTO Country (name, code) values ('South Sudan','SS ');
INSERT INTO Country (name, code) values ('Spain','ES ');
INSERT INTO Country (name, code) values ('Sri Lanka','LK ');
INSERT INTO Country (name, code) values ('Sudan','SD ');
INSERT INTO Country (name, code) values ('Suriname *','SR ');
INSERT INTO Country (name, code) values ('Svalbard and Jan Mayen Islands','SJ ');
INSERT INTO Country (name, code) values ('Swaziland','SZ ');
INSERT INTO Country (name, code) values ('Sweden','SE ');
INSERT INTO Country (name, code) values ('Switzerland','CH ');
INSERT INTO Country (name, code) values ('Syrian Arab Republic (Syria)','SY ');
INSERT INTO Country (name, code) values ('Taiwan, Republic of China','TW ');
INSERT INTO Country (name, code) values ('Tajikistan','TJ ');
INSERT INTO Country (name, code) values ('Tanzania *, United Republic of','TZ ');
INSERT INTO Country (name, code) values ('Thailand','TH ');
INSERT INTO Country (name, code) values ('Timor-Leste','TL ');
INSERT INTO Country (name, code) values ('Togo','TG ');
INSERT INTO Country (name, code) values ('Tokelau','TK ');
INSERT INTO Country (name, code) values ('Tonga','TO ');
INSERT INTO Country (name, code) values ('Trinidad and Tobago','TT ');
INSERT INTO Country (name, code) values ('Tunisia','TN ');
INSERT INTO Country (name, code) values ('Turkey','TR ');
INSERT INTO Country (name, code) values ('Turkmenistan','TM ');
INSERT INTO Country (name, code) values ('Turks and Caicos Islands','TC ');
INSERT INTO Country (name, code) values ('Tuvalu','TV ');
INSERT INTO Country (name, code) values ('Uganda','UG ');
INSERT INTO Country (name, code) values ('Ukraine','UA ');
INSERT INTO Country (name, code) values ('United Arab Emirates','AE ');
INSERT INTO Country (name, code) values ('United Kingdom','GB ');
INSERT INTO Country (name, code) values ('United States of America','US ');
INSERT INTO Country (name, code) values ('United States Minor Outlying Islands','UM ');
INSERT INTO Country (name, code) values ('Uruguay','UY ');
INSERT INTO Country (name, code) values ('Uzbekistan','UZ ');
INSERT INTO Country (name, code) values ('Vanuatu','VU ');
INSERT INTO Country (name, code) values ('Venezuela (Bolivarian Republic of)','VE ');
INSERT INTO Country (name, code) values ('Viet Nam','VN ');
INSERT INTO Country (name, code) values ('Virgin Islands, US','VI ');
INSERT INTO Country (name, code) values ('Wallis and Futuna Islands','WF ');
INSERT INTO Country (name, code) values ('Western Sahara','EH ');
INSERT INTO Country (name, code) values ('Yemen','YE ');
INSERT INTO Country (name, code) values ('Zambia','ZM ');
INSERT INTO Country (name, code) values ('Zimbabwe','ZW ');