
CREATE TABLE  CORRUPTION_INDEX (
     id bigint auto_increment,
     country_name   varchar (50) NOT NULL,
     idx_year  int,
     idx_val  float
);

INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Denmark',2014,92);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Denmark',2015,91);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Denmark',2016,92);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Finland',2014,90);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Finland',2015,89);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Finland',2016,89);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sweden',2014,89);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sweden',2015,87);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sweden',2016,89);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('New Zealand',2014,91);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('New Zealand',2015,91);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('New Zealand',2016,88);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Netherlands',2014,83);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Netherlands',2015,83);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Netherlands',2016,87);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Norway',2014,86);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Norway',2015,86);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Norway',2016,87);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Switzerland',2014,85);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Switzerland',2015,85);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Switzerland',2016,86);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Singapore',2014,86);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Singapore',2015,84);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Singapore',2016,85);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Canada',2014,81);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Canada',2015,81);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Canada',2016,83);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Germany',2014,78);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Germany',2015,79);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Germany',2016,81);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Luxembourg',2014,80);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Luxembourg',2015,82);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Luxembourg',2016,81);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United Kingdom',2014,76);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United Kingdom',2015,78);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United Kingdom',2016,81);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Australia',2014,81);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Australia',2015,80);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Australia',2016,79);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iceland',2014,78);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iceland',2015,79);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iceland',2016,79);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Belgium',2014,75);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Belgium',2015,76);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Belgium',2016,77);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Austria',2014,69);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Austria',2015,72);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Austria',2016,76);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United States',2014,73);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United States',2015,74);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United States',2016,76);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Hong Kong',2014,75);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Hong Kong',2015,74);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Hong Kong',2016,75);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ireland',2014,72);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ireland',2015,74);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ireland',2016,75);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Japan',2014,74);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Japan',2015,76);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Japan',2016,75);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uruguay',2014,73);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uruguay',2015,73);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uruguay',2016,74);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Qatar',2014,68);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Qatar',2015,69);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Qatar',2016,71);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Chile',2014,71);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Chile',2015,73);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Chile',2016,70);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Estonia',2014,68);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Estonia',2015,69);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Estonia',2016,70);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('France',2014,71);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('France',2015,69);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('France',2016,70);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United Arab Emirates',2014,69);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United Arab Emirates',2015,70);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('United Arab Emirates',2016,70);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bhutan',2014,63);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bhutan',2015,65);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bhutan',2016,65);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Botswana',2014,64);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Botswana',2015,63);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Botswana',2016,63);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Portugal',2014,62);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Portugal',2015,63);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Portugal',2016,63);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Poland',2014,60);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Poland',2015,61);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Poland',2016,62);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Taiwan',2014,61);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Taiwan',2015,61);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Taiwan',2016,62);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cyprus',2014,61);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cyprus',2015,63);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cyprus',2016,63);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Israel',2014,61);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Israel',2015,60);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Israel',2016,61);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lithuania',2014,57);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lithuania',2015,58);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lithuania',2016,61);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Slovenia',2014,57);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Slovenia',2015,58);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Slovenia',2016,60);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Spain',2014,59);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Spain',2015,60);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Spain',2016,58);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Czech Republic',2014,48);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Czech Republic',2015,51);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Czech Republic',2016,56);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Korea (South',2014,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Korea (South',2015,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Korea (South',2016,56);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malta',2014,56);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malta',2015,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malta',2016,56);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cape Verde',2014,58);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cape Verde',2015,57);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cape Verde',2016,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Costa Rica',2014,53);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Costa Rica',2015,54);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Costa Rica',2016,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Latvia',2014,53);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Latvia',2015,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Latvia',2016,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Seychelles',2014,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Seychelles',2015,55);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Seychelles',2016,54);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Rwanda',2014,53);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Rwanda',2015,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Rwanda',2016,54);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Jordan',2014,45);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Jordan',2015,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Jordan',2016,53);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mauritius',2014,52);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mauritius',2015,54);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mauritius',2016,53);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Namibia',2014,48);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Namibia',2015,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Namibia',2016,53);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Georgia',2014,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Georgia',2015,52);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Georgia',2016,52);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Saudi Arabia',2014,46);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Saudi Arabia',2015,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Saudi Arabia',2016,52);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bahrain',2014,48);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bahrain',2015,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bahrain',2016,51);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Croatia',2014,48);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Croatia',2015,48);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Croatia',2016,51);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Hungary',2014,54);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Hungary',2015,54);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Hungary',2016,51);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Slovakia',2014,47);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Slovakia',2015,50);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Slovakia',2016,51);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malaysia',2014,50);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malaysia',2015,52);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malaysia',2016,50);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kuwait',2014,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kuwait',2015,44);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kuwait',2016,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cuba',2014,46);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cuba',2015,46);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cuba',2016,47);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ghana',2014,46);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ghana',2015,47);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ghana',2016,48);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Greece',2014,40);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Greece',2015,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Greece',2016,46);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Romania',2014,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Romania',2015,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Romania',2016,46);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Oman',2014,47);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Oman',2015,45);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Oman',2016,45);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Italy',2014,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Italy',2015,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Italy',2016,47);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lesotho',2014,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lesotho',2015,49);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lesotho',2016,44);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Montenegro',2014,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Montenegro',2015,44);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Montenegro',2016,44);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Senegal',2014,41);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Senegal',2015,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Senegal',2016,44);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('South Africa',2014,44);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('South Africa',2015,44);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('South Africa',2016,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sao Tome and Principe',2014,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sao Tome and Principe',2015,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sao Tome and Principe',2016,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('The FYR of Macedonia',2014,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('The FYR of Macedonia',2015,45);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('The FYR of Macedonia',2016,44);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Turkey',2014,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Turkey',2015,45);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Turkey',2016,50);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bulgaria',2014,41);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bulgaria',2015,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bulgaria',2016,41);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Jamaica',2014,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Jamaica',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Jamaica',2016,41);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Serbia',2014,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Serbia',2015,41);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Serbia',2016,40);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('El Salvador',2014,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('El Salvador',2015,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('El Salvador',2016,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mongolia',2014,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mongolia',2015,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mongolia',2016,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Panama',2014,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Panama',2015,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Panama',2016,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Trinidad and Tobago',2014,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Trinidad and Tobago',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Trinidad and Tobago',2016,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bosnia and Herzegovina',2014,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bosnia and Herzegovina',2015,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bosnia and Herzegovina',2016,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Brazil',2014,42);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Brazil',2015,43);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Brazil',2016,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Burkina Faso',2014,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Burkina Faso',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Burkina Faso',2016,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('India',2014,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('India',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('India',2016,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Thailand',2014,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Thailand',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Thailand',2016,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tunisia',2014,41);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tunisia',2015,40);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tunisia',2016,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Zambia',2014,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Zambia',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Zambia',2016,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Benin',2014,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Benin',2015,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Benin',2016,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('China',2014,40);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('China',2015,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('China',2016,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Colombia',2014,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Colombia',2015,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Colombia',2016,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Liberia',2014,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Liberia',2015,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Liberia',2016,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('CoSri Lankalombia',2014,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('CoSri Lankalombia',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('CoSri Lankalombia',2016,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Albania',2014,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Albania',2015,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Albania',2016,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Algeria',2014,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Algeria',2015,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Algeria',2016,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Egypt',2014,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Egypt',2015,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Egypt',2016,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Indonesia',2014,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Indonesia',2015,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Indonesia',2016,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Morocco',2014,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Morocco',2015,39);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Morocco',2016,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Peru',2014,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Peru',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Peru',2016,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Suriname',2014,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Suriname',2015,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Suriname',2016,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Armenia',2014,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Armenia',2015,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Armenia',2016,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mali',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mali',2015,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mali',2016,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mexico',2014,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mexico',2015,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mexico',2016,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Philippines',2014,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Philippines',2015,38);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Philippines',2016,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bolivia',2014,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bolivia',2015,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bolivia',2016,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Djibouti',2014,36);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Djibouti',2015,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Djibouti',2016,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Gabon',2014,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Gabon',2015,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Gabon',2016,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Niger',2014,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Niger',2015,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Niger',2016,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Dominican Republic',2014,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Dominican Republic',2015,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Dominican Republic',2016,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ethiopia',2014,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ethiopia',2015,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ethiopia',2016,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kosovo',2014,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kosovo',2015,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kosovo',2016,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Moldova',2014,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Moldova',2015,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Moldova',2016,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Argentina',2014,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Argentina',2015,34);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Argentina',2016,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Belarus',2014,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Belarus',2015,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Belarus',2016,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cote dIvoire',2014,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cote dIvoire',2015,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cote dIvoire',2016,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ecuador',2014,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ecuador',2015,35);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ecuador',2016,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Togo',2014,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Togo',2015,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Togo',2016,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Honduras',2014,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Honduras',2015,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Honduras',2016,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malawi',2014,37);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malawi',2015,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Malawi',2016,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mauritania',2014,30);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mauritania',2015,30);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mauritania',2016,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mozambique',2014,30);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mozambique',2015,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Mozambique',2016,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Vietnam',2014,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Vietnam',2015,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Vietnam',2016,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Pakistan',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Pakistan',2015,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Pakistan',2016,30);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tanzania',2014,33);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tanzania',2015,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tanzania',2016,30);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Azerbaijan',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Azerbaijan',2015,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Azerbaijan',2016,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guyana',2014,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guyana',2015,30);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guyana',2016,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Russia',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Russia',2015,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Russia',2016,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sierra Leone',2014,30);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sierra Leone',2015,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sierra Leone',2016,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Gambia',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Gambia',2015,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Gambia',2016,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guatemala',2014,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guatemala',2015,32);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guatemala',2016,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kazakhstan',2014,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kazakhstan',2015,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kazakhstan',2016,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kyrgyzstan',2014,24);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kyrgyzstan',2015,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kyrgyzstan',2016,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lebanon',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lebanon',2015,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Lebanon',2016,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Madagascar',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Madagascar',2015,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Madagascar',2016,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cameroon',2014,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cameroon',2015,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cameroon',2016,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iran',2014,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iran',2015,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iran',2016,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nepal',2014,31);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nepal',2015,29);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nepal',2016,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nicaragua',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nicaragua',2015,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nicaragua',2016,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Paraguay',2014,24);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Paraguay',2015,24);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Paraguay',2016,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ukraine',2014,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ukraine',2015,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Ukraine',2016,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Comoros',2014,28);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Comoros',2015,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Comoros',2016,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nigeria',2014,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nigeria',2015,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Nigeria',2016,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tajikistan',2014,22);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tajikistan',2015,23);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Tajikistan',2016,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bangladesh',2014,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bangladesh',2015,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Bangladesh',2016,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guinea',2014,24);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guinea',2015,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guinea',2016,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kenya',2014,27);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kenya',2015,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Kenya',2016,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Laos',2014,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Laos',2015,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Laos',2016,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Papua New Guinea',2014,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Papua New Guinea',2015,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Papua New Guinea',2016,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uganda',2014,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uganda',2015,26);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uganda',2016,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Central African Republic',2014,25);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Central African Republic',2015,24);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Central African Republic',2016,24);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Congo Republic',2014,22);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Congo Republic',2015,23);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Congo Republic',2016,23);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Chad',2014,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Chad',2015,22);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Chad',2016,22);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Democratic Republic of the Congo',2014,22);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Democratic Republic of the Congo',2015,22);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Democratic Republic of the Congo',2016,22);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Burundi',2014,21);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Burundi',2015,20);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Burundi',2016,21);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cambodia',2014,20);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cambodia',2015,21);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Cambodia',2016,21);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Zimbabwe',2014,21);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Zimbabwe',2015,21);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Zimbabwe',2016,21);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uzbekistan',2014,17);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uzbekistan',2015,18);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Uzbekistan',2016,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Syria',2014,17);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Syria',2015,18);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Syria',2016,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Turkmenistan',2014,17);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Turkmenistan',2015,17);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Turkmenistan',2016,18);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Yemen',2014,18);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Yemen',2015,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Yemen',2016,18);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Haiti',2014,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Haiti',2015,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Haiti',2016,17);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guinea-Bissau',2014,18);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guinea-Bissau',2015,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Guinea-Bissau',2016,17);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Venezuela',2014,20);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Venezuela',2015,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Venezuela',2016,17);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iraq',2014,16);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iraq',2015,16);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Iraq',2016,16);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Libya',2014,15);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Libya',2015,18);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Libya',2016,16);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Angola',2014,23);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Angola',2015,19);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Angola',2016,15);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('South Sudan',2014,14);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('South Sudan',2015,15);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('South Sudan',2016,15);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sudan',2014,11);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sudan',2015,11);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Sudan',2016,12);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Afghanistan ',2014,8);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Afghanistan ',2015,12);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Afghanistan ',2016,11);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Korea (North',2014,8);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Korea (North',2015,8);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Korea (North',2016,8);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Somalia',2014,8);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Somalia',2015,8);
INSERT INTO CORRUPTION_INDEX (country_name, idx_year, idx_val) values ('Somalia',2016,8);